### ISSUE TITLE
Error when changing value

### ISSUE THREAD

**Issue by shumafuk** [GraySquyd/DOS2-DE-BetterCamera#1]
I have error whenever I tried to change any value.
`
Error:[string "--Uncomment the following line if this is a C..."]:424: attempt to perform arithmetic on a nil value`

Any idea what could be wrong? GoG version.

**Comment by Reenuip** [comment]
Same here. Here's a screenshot of the error output
![image](https://github.com/GraySquyd/DOS2-DE-BetterCamera/assets/54191569/3d4b6471-2744-4230-b5ac-4d802b221d34)
I tried just using Cheat Engine and loading the table manually. Same behavior on all recent versions of the table. I even replaced the Lua script section with the latest main.lua that was updated 2 days ago and it still doesn't work.

**Comment by Squydy** [comment]
Doesn't Support GOG sorry

**Comment by shumafuk** [comment]
You should support DRM free version of game.
