### ISSUE TITLE
Dialogue Zoom Disable function doesn't work after I escape from Dallis at Lady Vengeance

### ISSUE THREAD

**Issue by lightingflame** [GraySquyd/DOS2-DE-BetterCamera#2]
Hi GraySquyd, Love your work on this camera tool, especially the function of “Dialogue Zoom Disable”, it really helped me a lot while I was replay DOS2, it worked perfectly on the first map of Fort Joy, however after I escaped from Dallis at Lady Vengeance, entered into the map of The High Seas, it seems didn't work anymore, even I entered into the next map of Reaper's Coast , the camera still remain zoom out after dialogue, I wonder is there any way to fix it.

**Comment by Squydy** [comment]
I didn't test this that much since I didn't use it, I'll have to take a look.

**Comment by lightingflame** [comment]
Ok, thank you for your help!
