### ISSUE TITLE
Where can I find the guide to make this work with the GOG version?

### ISSUE THREAD

**Issue by taboo180** [GraySquyd/DOS2-DE-BetterCamera#3]
Hi!

I desperately want to get camera tilt working with my controller on the GOG version. On the Steam page for this mod you say _"Im not sure if it works with the GOG version, but you can always make it work by looking at the guide"_, where can I find this guide? 😊

Thanks!

**Comment by Squydy** [comment]
The guide I'm referring to is one I wrote. This was made using cheat engine, so the guide is in the original cheat table file (.ct). When opened in cheat engine there's a button in the lower right that says table extras. This guide explains how I found an offset, eocapp.exe+####### these pound signs, and how you can find it yourself using cheat engine. I never had the gog version otherwise I would've done it myself. The good news is once you find this offset everything should work just fine once you replace it in the lua script. You can even share the offset here and I can release a gog version.

**Comment by Squydy** [comment]
Didn't mean to close issue

**Comment by taboo180** [comment]
Thanks so much! I'm experimenting with it now. I believe I've followed your instructions correctly but when I search for "f:5.5 f:19 f:19" I get zero hits. If I search for just "f:19 f:19" I get the following:

[image removed]

Just making sure I'm not doing anything obviously wrong.

Thanks!

**Comment by Squydy** [comment]
You need to be playing the game lol. Open the game and open your save. Then attach cheat engine to the running process. You should see it in the process list window and shouldn't need to use "open file". Try f:5.5 f:5.5 f:19 f:19, they're two of min and max distance if you're still having problems. Also your email is showing on this image :)

**Comment by taboo180** [comment]
Champion! Took a bit of inference but I got there in the end! This is the rax for the GOG release, v3.6.117.3735:

![image](https://github.com/GraySquyd/DOS2-DE-BetterCamera/assets/47477508/10a55bd7-df69-42eb-af1a-e969d8ca2c4d)

And awesome spot on the email address ;) thanks!

**Comment by Squydy** [comment]
Good work, ive added a gog version to release page. Hopefully it works

**Comment by taboo180** [comment]
Confirmed working on mine:
![image](https://github.com/GraySquyd/DOS2-DE-BetterCamera/assets/47477508/b875adfd-762b-4fea-8f70-4026a7582a16)

Man, I've been looking for a GOG compatible version of "BetterCamera" for years. So glad I found your version and was able to "do it myself". Thank you.

**Comment by Squydy** [comment]
Fantastic! Glad it works, this is why I enjoy making modding tools for people. Glad this could be the solution that worked and is now available to everyone.

For future reference for this repository this is how you update my tool and the original tool. This is the same method for Better Camera 2 and 3. This value found is the "rax" in both programs. Just a variable name doesn't actually have to do anything with registers. 2959898 for Steam and 028F33F8 for GOG
